[IMP] estate: Grant full permissions to base.group_user T#71276
ralberrto/vauxoo-training pull request #2
Opened 2023-04-25 22:22 UTC by ralberrto

- Specify access to model.
- Add .act_window action in tree and form mode.
- Add menu with \<menuitem\> shortcut.
- Modify and further specify some fields.

2023-04-25 22:23 UTC, ralberrto commented
Hi @edy1192 I hope you're doing well. Could you please checkout this PR and merge if everything's OK? Thank you.

2023-04-25 22:52 UTC, edy1192 requested changes

2023-04-25 22:52 UTC, edy1192 commented on estate/views/estate_menus.xml
> +        <menuitem id="estate_first_level_menu" name="Actions">
```suggestion
        <menuitem id="estate_first_level_menu" name="Advertisements">
```

This is the goal of this chapter

![image](https://user-images.githubusercontent.com/11479473/234418959-c7bea5e7-c023-4de9-b0ed-96eb2a95a263.png)

2023-04-25 22:52 UTC, edy1192 commented on estate/views/estate_menus.xml
> +</odoo>
Please add a blank line at the end of the file. You can run `pre-commit-vauxoo -t all` and it fixes it for you.

2023-04-25 22:52 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +</odoo>
Same here, blank line, please.

2023-04-25 22:52 UTC, edy1192 commented on estate/models/estate_property.py
> +    name = fields.Char(required=True, default="Unknown")
If you add a default value for a field then the required attribute does not make sense because the field always will have a value. Also, this is not part of the exercise, it's just an example. 

![image](https://user-images.githubusercontent.com/11479473/234420029-f1d3e2ca-b366-4740-a897-f0329ba3b877.png)

2023-04-25 22:52 UTC, edy1192 commented on estate/models/estate_property.py
> +    )
```suggestion
    garden_orientation = fields.Selection(
        selection=[
            ("north", "North"),
            ("south", "South"),
            ("east", "East"),
            ("west", "West"),
        ]
    )
```
Run pre-commit-vauxoo to get the right format for this field, please.

2023-04-25 22:52 UTC, edy1192 commented on estate/models/estate_property.py
> +    )
```suggestion
    status = fields.Selection(
        selection=[
            ("new", "New"),
            ("offer_received", "Offer Received"),
            ("offer_accepted", "Offer Accepted"),
            ("sold", "Sold"),
            ("canceled", "Canceled"),
        ]
    )
```
Same here, run pre-commit-vauxoo -t all. Also the exercise says: 

` It must be required, should not be copied and should have its default value set to ‘New’.` , I don't see that.

2023-04-25 22:52 UTC, edy1192 commented on estate/views/estate_menus.xml
> +    <menuitem id="estate_menu_root" name="Real Estate ✨">
I'm sorry I like the emoji but it is not something that is used for menus.

```suggestion
    <menuitem id="estate_menu_root" name="Real Estate">
```

2023-04-25 23:07 UTC, ralberrto commented on estate/views/estate_menus.xml
> +</odoo>
I'm not sure what's happening with this one, I can see the new line in my editor, and running `pre-commit-vauxoo -t all` doesn't complain. I can add another one, if necessary.

2023-04-25 23:10 UTC, edy1192 commented on estate/models/estate_property.py
> +        copy=False, default=lambda self: fields.Date.add(fields.Date.today(), **{"months": 3})
```suggestion
        copy=False, default=lambda self: fields.Date.add(fields.Date.today(), months=3),
```

2023-04-25 23:12 UTC, ralberrto commented on estate/views/estate_menus.xml
> +    <menuitem id="estate_menu_root" name="Real Estate ✨">
):

2023-04-25 23:14 UTC, edy1192 commented on estate/views/estate_menus.xml
> +</odoo>
Mmm, maybe it's GitHub that is playing with us 😆

2023-04-25 23:40 UTC, ralberrto commented
Hey @edy1192 thank you for your comments. I made the corrections and I did run `pre-commit-vauxoo -t all` before commiting. It deleted the extra spaces at the end of the files, so those blank lines will probably appear to be missing still. I'm not sure why this is happening. I will be expecting your comments. Thank you!

2023-04-26 00:03 UTC, edy1192 requested changes

2023-04-26 00:03 UTC, edy1192 commented on estate/models/estate_property.py
> +    )
You missed this.

2023-04-26 00:03 UTC, edy1192 commented on estate/models/estate_property.py
> +    )
First is the selection options and then attributes.
```suggestion
    status = fields.Selection(
        selection=[
            ("new", "New"),
            ("offer_received", "Offer Received"),
            ("offer_accepted", "Offer Accepted"),
            ("sold", "Sold"),
            ("canceled", "Canceled"),
        ],
        required=True,
        copy=False,
        default="new",
    )
```

2023-04-26 22:13 UTC, deivislaya commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action" />
```suggestion
            <menuitem id="estate_model_menu_action" action="estate_property_action" name="Properties"/>
```

![Chapter-6-Finally-Some-UI-To-Play-With-—-Odoo-16-0-documentation](https://user-images.githubusercontent.com/5775695/234714177-c7712520-daa9-4e09-8762-ffbbef643639.png)

2023-04-26 22:20 UTC, ralberrto commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action" />
Thank you for your comments @deivislaya the name is actually in the referenced action. Should I redundantly put it in a name tag too? 
![image](https://user-images.githubusercontent.com/77471210/234715413-9369a571-4277-4218-aa9c-818b08b37fe6.png)

2023-04-26 22:21 UTC, deivislaya commented
- Please, add file readme.rst 

- Adjust commit's title [guideline](https://www.odoo.com/documentation/16.0/es/contributing/development/git_guidelines.html#commit-message-structure)

> Before
> 
> [IMP] estate: Grant full permissions to base.group_user T#71276
> 
> Expected
> 
> [IMP] estate: grant full permissions to base.group_user T#71276

2023-04-28 01:24 UTC, deivislaya commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action" />
Yes, that's correct, it only applies if the action name differs from the menu string, but these are exceptional cases. It will take the value of the menu

2023-05-02 17:09 UTC, edy1192 requested changes

2023-05-02 17:09 UTC, edy1192 commented on .gitignore
> +logging.out
Why this folders here?

2023-05-02 17:09 UTC, edy1192 commented on estate/README.rst
> +---
This seem to be wrong. See the final result of the file

![image](https://user-images.githubusercontent.com/11479473/235735461-7bf0cce8-111b-43dd-88d0-6cec995e144d.png)



```suggestion
# Real Estate
------------------
```

2023-05-02 17:09 UTC, edy1192 commented on estate/README.rst
> +This module is developed during the Odoo training at Vauxoo.
```suggestion
This module is developed during the training of Odoo in Vauxoo.
```

2023-05-02 17:09 UTC, edy1192 commented on estate/models/estate_property.py
> +    selling_price = fields.Float(readonly=True, copy=False)
Attributes should be organized alphabetically.

```suggestion
    selling_price = fields.Float(copy=False, readonly=True)
```

2023-05-02 17:09 UTC, edy1192 commented on estate/models/estate_property.py
> +    )
```suggestion
    status = fields.Selection(
        selection=[
            ("new", "New"),
            ("offer_received", "Offer Received"),
            ("offer_accepted", "Offer Accepted"),
            ("sold", "Sold"),
            ("canceled", "Canceled"),
        ],
        copy=False,
        default="new",
        required=True,
    )
```

2023-05-02 18:01 UTC, ralberrto commented on .gitignore
> +logging.out
These are soft links, they're there just to make it easier run the internal server, I just have to write now: `odoo --addons-path=training,enterprise,odooaddons -d rd-demo -u estate --logfile ./logging.out --dev xml`

2023-05-02 18:41 UTC, ralberrto commented
@edy1192 Hi Edy, the requested corrections have been made. Can you please take a look?

2023-05-02 18:49 UTC, edy1192 commented on estate/README.rst
> +-----------------
```suggestion
# Real Estate
-----------------
```

I don't know why in the file I see the - after the word estate and in the suggestion it looks good. I'm going to accept it like this for now but in the next PR please correct it, the - goes right up to the last letter of the text.

2023-05-02 18:51 UTC, edy1192 commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action" />
The ids must have intuitive names or that have to do with what we do.

```suggestion
        <menuitem id="estate_advertisement_menu" name="Advertisements">
            <menuitem id="estate_property_menu" action="estate_property_action" />
```

2023-05-02 20:25 UTC, ralberrto commented
@edy1192 Hi Edy, the requested changes are ready, would you please check them out? Thank you!

2023-05-02 21:05 UTC, edy1192 approved these changes

2023-05-02 21:05 UTC, merged