[IMP] estate: add computed fields and onchange events T#71276
ralberrto/vauxoo-training pull request #6
Opened 2023-05-05 17:16 UTC by ralberrto

- Add total_area computed field and include it in form view
- Add best_price computed field and include it in form view
- Add interdependent (computed and inverted) fields to model and display them
- Add onchange event to garden field
- Add actions to change status in EstateProperty model
- Compute selling_price and buyer_id fields based on EstatePropertyOffer model

2023-05-05 18:24 UTC, edy1192 requested changes

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property.py
> +            record.buyer_id = None
Why these computed fields? The exercise says: 

> **When an offer is accepted**, set the buyer and the selling price for the corresponding property.

You can make the assignment of these fields in the accept offer button and avoid making an additional calculation. You have to be very careful with the computed fields, if they are not reasoned well they can greatly affect performance.

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property.py
> +            self.garden_area = None
```suggestion
            self.garden_area = 0
```

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property.py
> +    def set_status_canceled(self):
By convention, we always call this type of action `action_something`

Check the documentation.

![image](https://user-images.githubusercontent.com/11479473/236533957-b96ef394-b364-44dc-92a0-c8accbafb514.png)

Apply this suggestion in all the same occurrences.

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property.py
> +                raise exceptions.UserError(_("Sold properties cannot be canceled."))
Why do you use the method `_()`? Do you know what that method does?

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property.py
> +                raise exceptions.UserError(_("Canceled properties cannot be sold."))
Same here why `_()`?

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +            if sum(record.property_id.offer_ids.mapped(lambda x: x.status == "accepted")):
Why you sum this? You could do:

```suggestion
            if "accepted" in record.property_id.offer_ids.mapped("status"):
```

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +                offer.status = "refused"
Why this for? The exercise says nothing about rejecting all offers. I think this is not necessary.

2023-05-05 18:24 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +            record.status = "refused"
You could avoid the for, using the [write](https://www.odoo.com/documentation/16.0/developer/reference/backend/orm.html#odoo.models.Model.write) method. Please read about it.

```suggestion
        self.write({'status': "refused"})
```

2023-05-05 19:08 UTC, ralberrto commented on estate/models/estate_property.py
> +                record.best_price = None
In regards to point 1. The internal server failed because the value of the fields was not assigned in the compute method. Than happens when the condition is skipped, and that's the reason I decided to assign `None`. Any work around this matter?

In regards to point 3. I will change integrate those changes rightaway.

2023-05-05 19:09 UTC, ralberrto commented on estate/models/estate_property.py
> +            record.buyer_id = None
I got it. I see my mistake now, thanks a lot.

2023-05-05 19:12 UTC, ralberrto commented on estate/models/estate_property_offer.py
> +                offer.status = "refused"
I misinterpreted the result depicted by the images in the assignment. I'll fix it.

2023-05-05 19:25 UTC, edy1192 commented on estate/models/estate_property.py
> +                record.best_price = None
You're right. In previous versions, the computed fields could be left unassigned, but in the latest version, they always have to be assigned. Sorry, I didn't remember that. Assign it 0 instead of None, please.

2023-05-05 22:11 UTC, ralberrto commented
Hi @edy1192 the requirements have been met. Could you please take a minute to review them? Thanks!

2023-05-05 23:01 UTC, edy1192 requested changes

2023-05-08 14:43 UTC, ralberrto commented on estate/models/estate_property_offer.py
> +            record.validity = (record.date_deadline - record.create_date.date()).days
I sure will, thank you!

2023-05-08 21:18 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +            record.validity = (record.date_deadline - record.create_date.date()).days
Yes, the result you obtained is expected. I just wanted you to try it out to see if it was possible. Thank you!

2023-05-08 21:18 UTC, edy1192 approved these changes

2023-05-08 21:18 UTC, merged