[IMP] estate: add constraints and further refine UI T#71276
ralberrto/vauxoo-training pull request #7
Opened 2023-05-11 17:17 UTC by ralberrto

- Add required constraints to models
- Add constraints to validate offers expected and selling prices
- Add list of EstateProperties associated to PropertyTypes
- Add statusbar view to EstateProperty form
- Add db order to models
- Add sequence handler widget to PropertyTypes view
- Prevent creation/edition of PropertyTypes add color to PropetyTags
- Make the buttons in header vanish if property is sold or canceled
- Use attrs to hide fields, buttons, and make them readonly
- Make list views editable in-place
- Add decorations to entries based on fields' values
- Apply the **Available** filter associated to EstateProperty by default
- Add filter domain to the living_area field
- Add related field to PropertyOffer model
- Add computed field offer_count to PropertyType
- Add action and smart button linked to it filtering the view

2023-05-11 17:18 UTC, ralberrto commented
Hey @edy1192 this _PR_ is ready. Could you please check it out? Thank you!

2023-05-11 23:08 UTC, edy1192 requested changes

2023-05-11 23:08 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +                                <field attrs="{'invisible': [('garden', '=', False)]}" name="garden_orientation" />
First is the field name then attributes, options...

```suggestion
                                <field name="garden_area" attrs="{'invisible': [('garden', '=', False)]}" />
                                <field name="garden_orientation" attrs="{'invisible': [('garden', '=', False)]}" />
```

2023-05-11 23:08 UTC, edy1192 commented on estate/views/estate_property_offer_views.xml
> +                />
`attrs` is the last option that we add. 

```suggestion
                <button
                    icon="fa-check"
                    name="action_set_status_accepted"
                    string="Accept"
                    type="object"
                    attrs="{'invisible': ['|', ('status', '=', 'accepted'), ('status', '=', 'refused')]}"
                />
                <button
                    icon="fa-times"
                    name="action_set_status_refused"
                    string="Refuse"
                    type="object"
                    attrs="{'invisible': ['|', ('status', '=', 'accepted'), ('status', '=', 'refused')]}"
                />
```

2023-05-11 23:08 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +                <field name="status" optional="hide" />
Why optional hide? I did not see an exercise that says that.

2023-05-12 16:21 UTC, ralberrto commented
Hi @edy1192 I just finished making the necessary changes. Can you please check them out? Thank you!

2023-05-12 23:39 UTC, edy1192 commented on estate/models/estate_property.py
> +            ) and record.selling_price != 0:
Got it.

2023-05-12 23:46 UTC, edy1192 requested changes

2023-05-12 23:46 UTC, edy1192 commented on estate/views/estate_property_type_views.xml
> +                            <field name="offer_ids" widget="statinfo" string="Offers" />
This should be the `offer_count` field.
```suggestion
                            <field name="offer_count" widget="statinfo" string="Offers" />
```

2023-05-12 23:46 UTC, edy1192 commented on estate/models/estate_property_type.py
> +            "A property type with the same name already exists",
Pending.

2023-05-12 23:46 UTC, edy1192 commented on estate/models/estate_property_type.py
> +            "property_type_name_unique",
Pending.

2023-05-12 23:46 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +    property_type_id = fields.Many2one(related="property_id.property_type_id")
Pending.

2023-05-15 15:25 UTC, ralberrto commented
Hey @edy1192 the changes have been completed. Would you please check them out?

2023-05-15 15:36 UTC, edy1192 approved these changes

2023-05-15 15:36 UTC, merged